    <?php $billingAddress = $this->getCartBillingAddress()->getData(); ?>
    <?php $shippingAddress = $this->getCartShippingAddress()->getData(); ?>
    <?php //echo "<pre>"; print_r($billingAddress); die();?>
    <div id="order-addresses">
        <div id="order-billing_address" class="box-left">
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head fieldset-legend head-billing-address">Billing Address</h4>
                    <div class="form-buttons">
                        <button id="submit_order_top_button" type="button" onclick="return validate('<?php echo $this->getSaveBillingUrl() ?>','b');" class="scalable save">
                            <span><span><span>Update</span></span></span>
                        </button>
                    </div>
                </div>
                <fieldset class="np">
                    <div id="order-shipping_address_choice" class="order-choose-address">&nbsp</div>
                    <div class="order-address" id="order-billing_address_fields">
                        <div class="content">
                            <div class="hor-scroll">
                                <table id="billing" cellspacing="0" class="form-list">
                                    <tbody>
                                        <tr>
                                            <td class="label"><label for="first_name">First Name <span class="required">*</span></label></td>
                                            <td class="value">
                                                <input id="billing_first_name" name="billing[firstname]" value="<?php echo $this->getValue($billingAddress, 'firstname'); ?>" class="input-text required-entry" type="text" />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="label"><label for="last_name">Last Name <span class="required">*</span></label></td>
                                            <td class="value">
                                                <input id="billing_last_name" name="billing[lastname]" value="<?php echo $this->getValue($billingAddress, 'lastname'); ?>" class="input-text required-entry" type="text" />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="label"><label for="address">Street Address <span class="required">*</span></label></td>
                                            <td class="value">
                                                <input id="billing_address" name="billing[street]" value="<?php echo $this->getValue($billingAddress, 'street'); ?>" class="input-text required-entry" type="text" />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="label"><label for="city">City <span class="required">*</span></label></td>
                                            <td class="value">
                                                <input id="billing_city" name="billing[city]" value="<?php echo $this->getValue($billingAddress, 'city'); ?>" class=" required-entry input-text required-entry" type="text" />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="label"><label for="state">State/Province <span class="required">*</span></label></td>
                                            <td class="value">
                                                <input id="billing_state" name="billing[region]" value="<?php echo $this->getValue($billingAddress, 'region'); ?>" class="input-text" type="text" />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="label"><label for="country">Country <span class="required">*</span></label></td>
                                            <td class="value">
                                            <select id="billing_country" name="billing[country_id]" class="required-entry required-entry select">
                                                <?php foreach ($this->getCountryOptions() as $country) : ?>
                                                    <option value="<?php echo $country['value'] ?>" <?php if ($country['value'] == $this->getValue($billingAddress, 'country_id')){ echo "selected";} ?>><?php echo $country['label'] ?></option>
                                                <?php endforeach; ?>
                                            </select>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="label"><label for="zipcode">Zip/Postal Code <span class="required">*</span></label></td>
                                            <td class="value">
                                                <input id="billing_zipcode" name="billing[postcode]" value="<?php echo $this->getValue($billingAddress, 'postcode'); ?>" class=" required-entry input-text required-entry" type="text" />
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="order-save-in-address-book">
                            <input name="save_to_billing_address" type="checkbox" id="billingSaveToAddress" value="1" />
                            <label for="saveToAddress">Save in address book</label>
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>

        <div id="order-shipping_address" class="box-right">
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head fieldset-legend head-shipping-address">Shipping Address</h4>
                <div class="form-buttons">
                    <button id="submit_order_top_button" type="button" onclick="return validate('<?php echo $this->getShippingAddressUrl() ?>','s');" class="scalable save">
                        <span><span><span>Update</span></span></span>
                    </button>
                </div>
            </div>
            <fieldset class="np">
                <div id="order-shipping_address_choice" class="order-choose-address">
                    <input type="checkbox" <?php if($shippingAddress['same_as_billing']){echo "checked";} ?> id="sameAsBillingcheck" name="same_as_billing" onclick="return sameAsChecked()"/>
                    <label for="sameAsBilling" class="no-float">Same As Billing Address</label>
                </div>
                <div class="order-address" id="order-shipping_address_fields">
                    <div class="content">
                        <div class="hor-scroll">
                            <table id="shipping" cellspacing="0" class="form-list">
                                <tbody>
                                    <tr>
                                        <td class="label"><label for="first_name">First Name <span class="required">*</span></label></td>
                                        <td class="value">
                                            <input id="shipping_first_name" name="shipping[firstname]" value="<?php echo $this->getValue($shippingAddress, 'firstname'); ?>" class="input-text required-entry" type="text" />
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="label"><label for="last_name">Last Name <span class="required">*</span></label></td>
                                        <td class="value">
                                            <input id="shipping_last_name" name="shipping[lastname]" value="<?php echo $this->getValue($shippingAddress, 'lastname'); ?>" class="input-text required-entry" type="text" />
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="label"><label for="address">Street Address <span class="required">*</span></label></td>
                                        <td class="value">
                                            <input id="shipping_address" name="shipping[street]" value="<?php echo $this->getValue($shippingAddress, 'street'); ?>" class="input-text required-entry" type="text" />
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="label"><label for="city">City <span class="required">*</span></label></td>
                                        <td class="value">
                                            <input id="shipping_city" name="shipping[city]" value="<?php echo $this->getValue($shippingAddress, 'city'); ?>" class=" required-entry input-text" type="text" />
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="label"><label for="state">State/Province <span class="required">*</span></label></td>
                                        <td class="value"><input id="shipping_state" name="shipping[region]" value="<?php echo $this->getValue($shippingAddress, 'region'); ?>" class="input-text required-entry" type="text" /></td>
                                    </tr>
                                    <tr>
                                        <td class="label"><label for="country">Country <span class="required">*</span></label></td>
                                        <td class="value">
                                            <select id="shipping_country" name="shipping[country_id]" class="required-entry required-entry select">
                                                <?php foreach ($this->getCountryOptions() as $country) : ?>
                                                    <option value="<?php echo $country['value'] ?>" <?php if ($country['value'] == $this->getValue($shippingAddress, 'country_id')){ echo "selected";} ?>><?php echo $country['label'] ?></option>
                                                <?php endforeach; ?>
                                            </select>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="label"><label for="zipcode">Zip/Postal Code <span class="required">*</span></label></td>
                                        <td class="value">
                                            <input id="shipping_zipcode" name="shipping[postcode]" value="<?php echo $this->getValue($shippingAddress, 'postcode'); ?>" class=" required-entry input-text required-entry" type="text" />
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="order-save-in-address-book">
                        <input name="save_to_shipping_address" type="checkbox" id="shippingSaveToAddress" />
                        <label for="saveToAddress">Save in address book</label>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>

<script type="text/javascript">

    function sameAsChecked() {
        var billingAddress = document.getElementById('billing_address').value; 
        var billingzipcode = document.getElementById('billing_zipcode').value; 
        var billingCountry = document.getElementById('billing_country').value; 
        var billingState = document.getElementById('billing_state').value; 
        var billingCity = document.getElementById('billing_city').value; 
        var billingFname = document.getElementById('billing_first_name').value; 
        var billingLname = document.getElementById('billing_last_name').value; 
     
        if(billingAddress == '' || billingzipcode == ''|| billingCountry == '' || billingState == '' || billingCity == '' || billingFname == '' || billingLname == ''){
            alert('Please Fill the Billing Address First');
            return false;

        }
        var shippingAddress = document.getElementById('shipping_address'); 
        var shippingzipcode = document.getElementById('shipping_zipcode'); 
        var shippingCountry = document.getElementById('shipping_country'); 
        var shippingState = document.getElementById('shipping_state'); 
        var shippingCity = document.getElementById('shipping_city'); 
        var shippingFname = document.getElementById('shipping_first_name'); 
        var shippingLname = document.getElementById('shipping_last_name');

        shippingAddress.value = billingAddress;
        shippingLname.value = billingLname;
        shippingFname.value = billingFname;
        shippingzipcode.value = billingzipcode;
        shippingCountry.value = billingCountry;
        shippingState.value = billingState;
        shippingCity.value = billingCity;
    //  }      
    }
      // var sameAsBilling = document.getElementById('sameAsBillingcheck').value;
      // if(sameAsBilling == 1){
</script>