<?php $shipping = $this->getCartShippingAddress(); ?>
<?php $billing = $this->getCartBillingAddress(); ?>
<?php if($billing):?>
<?php $billing = $billing->getData();?>
<?php endif;?>
<?php if($shipping):?>
<?php $shipping = $shipping->getData();?>
<?php endif;?>
<div id="order-addresses">
<div id="order-billing_address" class="box-left">
<div class="entry-edit">

<div class="entry-edit-head">
    <h4 class="icon-head fieldset-legend head-billing-address">Billing Address</h4>
</div>
<?php //if($billing->getData()):?>
<fieldset class="np">
    <div class="order-address" id="order-billing_address_fields">
        <div class="content">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tbody>

                        <tr>
                            <td class="label"><label for="order-billing_address_street0">Street Address
                                    <span class="required">*</span></label></td>
                            <td class="value">
                                <div class="multi-input"><input id="order-billing_address_street0"
                                        name="billing[street]"
                                        value="<?php echo $billing['street']; ?>"
                                        class=" input-text required-entry" type="text">
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="label"><label for="order-shipping_address_postcode">Zip/Postal Code
                                    <span class="required">*</span></label></td>
                            <td class="value">
                                <input id="order-shipping_address_postcode"
                                    name="shipping[postcode]"
                                    value="<?php echo $billing['postcode']; ?>"
                                    class=" required-entry input-text required-entry" type="text"
                                    disabled="">
                            </td>
                        </tr>
                        <tr>
                            <td class="label"><label for="order-billing_address_state">State</label></td>
                            <td class="value">
                                <input id="order-billing_address_state" name="billing[region]"
                                    value="<?php echo $billing['region']; ?>"
                                    class="input-text" type="text">
                            </td>
                        </tr>
                        <tr>
                            <td class="label"><label for="order-billing_address_city">City <span
                                        class="required">*</span></label></td>
                            <td class="value">
                                <input id="order-billing_address_city" name="billing[city]"
                                    value="<?php echo $billing['city']; ?>"
                                    class=" required-entry input-text required-entry" type="text">
                            </td>
                        </tr>
                        <tr>
                            <td class="label"><label for="order-billing_address_country">Country<span
                                        class="required">*</span></label>
                            </td>
                            <td class="value">
                                <input id="order-billing_address_country"
                                    name="billing[country_id]"
                                    value="<?php echo $billing['country_id']; ?>"
                                    class="required-entry input-text" type="text">
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="order-save-in-address-book">
            <input name="billingAddressBook" type="checkbox"
                id="order-billing_address_save_in_address_book">
            <label for="order-billing_address_save_in_address_book">Save in address book</label>
        </div>
        <div class="form-group mt-3">
    		<button class="btn btn-success" type="button" onclick="object.resetParam().setUrl('<?= $this->getUrl('*/*/updateAddress',['id' => $this->getRequest()->getParam('id'),'type' => 'billing']) ?>').setParams(jQuery('#cartForm').serializeArray()).load()">Update</button>
		</div>
    </div>
<?php //endif; ?>
</fieldset>
</div>
</div>
<div id="order-shipping_address" class="box-right">
<div class="entry-edit" style="position: relative;">

<div class="entry-edit-head">
    <h4 class="icon-head fieldset-legend head-shipping-address">Shipping Address</h4>
</div>
<?php //if($shipping):?>
<fieldset class="np">

    <div class="order-address" id="order-shipping_address_fields">
        <div class="content">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tbody>
                        <tr>
                            <td>
                                <input name="sameAsBilling" type="checkbox"
                id="order-billing_address_same_as_billing"  checked>
                                <label for="order-billing_address_same_as_billing">Same as Billing</label>
                            </td>
                        </tr>
                        <tr>
                            <td class="label"><label for="order-shipping_address_street0">Street Address
                                    <span class="required">*</span></label></td>
                            <td class="value">
                                <div class="multi-input"><input id="order-shipping_address_street"
                                        name="shipping[street]"
                                        value="<?php echo $shipping['street']; ?>"
                                        class="input-text required-entry" type="text" disabled="">
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="label"><label for="order-shipping_address_postcode">Zip/Postal Code
                                    <span class="required">*</span></label></td>
                            <td class="value">
                                <input id="postcode"
                                    name="shipping[postcode]"
                                    value="<?php echo $shipping['postcode']; ?>"
                                    class=" required-entry input-text required-entry" type="text"
                                    disabled="">
                            </td>
                        </tr>
                        <tr>
                            <td class="label"><label for="order-shipping_address_city">City <span
                                        class="required">*</span></label></td>
                            <td class="value">
                                <input id="city" name="shipping[city]"
                                    value="<?php echo $shipping['city']; ?>"
                                    class=" required-entry input-text required-entry" type="text"
                                    disabled="">
                            </td>
                        </tr>
                        <tr>
                            <td class="label"><label for="order-shipping_address_state">State <span
                                        class="required">*</span></label></td>
                            <td class="value">
                                <input id="state"
                                    name="shipping[region]"
                                    value="<?php echo $shipping['region']; ?>"
                                    class=" required-entry input-text required-entry" type="text"
                                    disabled="">
                            </td>
                        </tr>
                        <tr>
                            <td class="label"><label for="order-shipping_address_country">Country<span
                                        class="required">*</span></label>
                            </td>
                            <td class="value">
                                <input id="country"
                                    name="shipping[country_id]"
                                    value="<?php echo $shipping['country_id']; ?>"
                                    class="required-entry input-text" type="text" disabled="">
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="order-save-in-address-book">
            <input name="shippingAddressBook" type="checkbox"
                id="order-shipping_address_save_in_address_book" value="1">
            <label for="order-shipping_address_save_in_address_book">Save in address book</label>
        </div>
        <div class="form-group mt-3">
    		<button class="btn btn-success" type="button" onclick="object.resetParam().setUrl('<?= $this->getUrl('*/*/updateAddress',['id' => $this->getRequest()->getParam('id'),'type' => 'shipping']) ?>').setParams(jQuery('#cartForm').serializeArray()).load()">Update</button>
		</div>
    </div>
<?php //endif; ?>
</fieldset>
</div>
</div>
</div>
