<?php $cart = $this->getCart(); ?>
<?php //echo "<pre>"; print_r($cart->getCartItems()); die();?>
<div class="entry-edit">
    <div class="entry-edit-head"><h4>Cart</h4></div>
    <fieldset class="bold">
		<?php if ($cart): ?>
			<?php $items = $cart->getCartItems(); ?>
			<table class="table">
				<tr>
					<td colspan="4"></td>
					<td><button type="button" class="btn btn-success" onclick="object.resetParam().setUrl('<?= $this->getUrl('*/adminhtml_order_cart/update') ?>').setParams(jQuery('#cartForm').serializeArray()).setMethod('POST').load()">Update Cart</button></td>
				</tr>
				<tr>
					<th>Product Name</th>
					<th>Quantity</th>
					<th>Price</th>
					<th>Discount</th>
					<th>Delete</th>
				</tr>
				
				<?php if ($items): ?>
					<?php foreach ($items->getData() as $item): ?>
						<tr>
							<td><?php echo $this->getItemObject()->getProduct()->name ?></td>
							<td><input type="number" class="form-control" name="quantity[<?= $item->cart_item_id ?>]" value="<?= $item['quantity'] ?>"></td>
							<td><?= $item['price'] ?></td>
							<td><?= $item['discount'] * $item['quantity'] ?></td>
							<td><button type="button" class="btn btn-danger" onclick="object.resetParam().setUrl('<?= $this->getUrl('*/adminhtml_order_cart/delete',['id' => $item['
								cart_item_id']]) ?>').setParams(jQuery('#cartForm').serializeArray()).setMethod('POST').load()">&times;</button></td>
						</tr>
					<?php endforeach ?>	
					<!-- <tr>
						<td colspan="3"></td>
						<td>Total :</td>
						<td>0.0</td>
					</tr> -->
				<?php else: ?>
					<tr>
						<td colspan="5" class="text-center">Cart is Empty</td>
					</tr>	
				<?php endif ?>
				
			</table>
		<?php endif ?>

</fieldset>
</div>