<?php $cartDetails = $this->getCart(); ?>

<div class="entry-edit">
    <div class="entry-edit-head"><h4>Cart Details</h4></div>
    <fieldset class="a-center bold">
		<table class="table mt-4 text-left">
			<tr>
				<td>
					Total :
				</td>
				<td>
					<?php if ($cartDetails): ?>
						$<?= $cartDetails->total ?>
					<?php else: ?>
						$0.00
					<?php endif ?>
				</td>
			</tr>
			<tr>
				<td>
					Shipping Charges :
				</td>
				<td>
					<?php if ($cartDetails): ?>
						$<?= $cartDetails->shippingAmount ?>
					<?php else: ?>
						$0.00
					<?php endif ?>
				</td>
			</tr>
			<tr>
				<td>
					Grand Total :
				</td>
				<td>
					<?php if ($cartDetails): ?>
						$<?= $cartDetails->total + $cartDetails->shippingAmount ?>
					<?php else: ?>
						$0.00
					<?php endif ?>
				</td>
			</tr>
			<tr>
				<td colspan="2">
					<button class="btn btn-success">Place Order</button>
				</td>
			</tr>
		</table>
	</fieldset>
</div>
