<?php $products = $this->getProducts(); ?>
<div id="products">
    <div id="order-search" class="order-search-items">
        <div class="entry-edit">
            <div class="entry-edit-head">
                <div style="float: right;">
                    <button title="Add Selected Product(s) to Order" type="button" onclick="changeAction('<?php echo $this->getUrl('*/adminhtml_order/addProduct',array('_current' => true)); ?>')" class="scalable add"><span><span><span>Add Selected Product(s) to Order</span></span></span></button>
                </div>
                <h4 class="fieldset-legend head-catalog-product icon-head">Please Select Products to Add</h4>
            </div>
            <div class="fieldset">

                <div id="sales_order_create_search_grid">
                    <table cellspacing="0" class="actions">
                <!--         <tr>
                            <td class="pager">
                                Page
                                <img src="http://127.0.0.1/phpCode/magento/skin/adminhtml/default/default/images/pager_arrow_left_off.gif" alt="Go to Previous page" class="arrow" />

                                <input type="text" name="page" value="1" class="input-text page" onkeypress="sales_order_create_search_gridJsObject.inputPage(event, '1')" />

                                <img src="http://127.0.0.1/phpCode/magento/skin/adminhtml/default/default/images/pager_arrow_right_off.gif" alt="Go to Next page" class="arrow" />

                                of 1 pages <span class="separator">|</span>
                                View <select name="limit" onchange="sales_order_create_search_gridJsObject.loadByElement(this)">
                                    <option value="20" selected="selected">20</option>
                                    <option value="30">30</option>
                                    <option value="50">50</option>
                                    <option value="100">100</option>
                                    <option value="200">200</option>
                                </select>
                                per page<span class="separator">|</span>
                                Total 2 records found <span id="sales_order_create_search_grid-total-count" class="no-display">2</span>
                            </td>
                            </tr> -->
                    </table>
                    <div class="grid">
                        <div class="hor-scroll">
                            <table cellspacing="0" class="data" id="sales_order_create_search_grid_table">
                                <col width="60" />
                                <col />
                                <col width="80" />
                                <col width="100" />
                                <col width="55" />
                                <col width="1" />
                                <thead style="background-color: rgb(111, 137, 146);">
                                    <th style="color:white;">ID</th>
                                    <th style="color:white;">Product Name</th>
                                    <th style="color:white;">SKU</th>
                                    <th style="color:white;">Price</th>
                                    <th style="color:white;">Select</th>
                                </thead>

                                <tbody>
                                    <?php foreach ($products as $key => $product) : ?>
                                        <tr title="#">
                                            <td class=" "><?php echo $product['entity_id']; ?></td>
                                            <td class=" "><?php echo $product['name']; ?></td>
                                            <td class=" "><?php echo $product['sku']; ?></td>
                                            <td class="a-center price a-right "><?php echo $product['price']; ?></td>
                                            <td class="a-center ">
                                                <input type="checkbox" name="products[]" value="<?php echo $product['entity_id']; ?>" class="checkbox" />
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>