<?php $shippingAddress = $this->getOrderShippingAddress(); ?>
<?php $billingAddress = $this->getOrderBillingAddress(); ?>
<?php //echo "<pre>"; print_r($this->getCountryName()); die();?>
<?php $countries = $this->getCountryName()?>
<?php $countryName = $billingAddress->getCountryId()?>
<div class="row">
	<div class="entry-edit box-left">
        <div class="entry-edit-head">
            <h4 class="icon-head head-billing-address">Billing Address</h4>
        </div>
        <fieldset>
            <address><?php echo $billingAddress->getFirstname().' '.$billingAddress->getLastname()?><br>
				<?php echo $billingAddress->getStreet();?><br>
				<?php echo $billingAddress->getCity();?> ,<?php echo $billingAddress->getRegion()?>, <?php echo $billingAddress->getPostcode()?><br>
				<?php foreach($countries as $key => $country):?>
					<?php if($country['country_id'] == $countryName):?>
					<?php echo $country['name']?><br>
				<?php endif;?>
				<?php endforeach;?>
			</address>
        </fieldset>
    </div>
    <div class="entry-edit box-right">
        <div class="entry-edit-head">
            <h4 class="icon-head head-shipping-address">Shipping Address</h4>
           
        </div>
        <fieldset>
            <address><?php echo $shippingAddress->getFirstname().' '.$shippingAddress->getLastname()?><br>
				<?php echo $shippingAddress->getStreet();?><br>
				<?php echo $shippingAddress->getCity();?> ,<?php echo $shippingAddress->getRegion()?>, <?php echo $shippingAddress->getPostcode()?><br>
				<?php foreach($countries as $key => $country):?>
					<?php if($country['country_id'] == $countryName):?>
					<?php echo $country['name']?><br>
				<?php endif;?>
				<?php endforeach;?>
			</address>
        </fieldset>
    </div>
	
</div>