<?php $statuses = $this->getStatuses();?>
<?php $orderStatus = $this->getOrder()->getOrderStatus();?>
<?php $currentStatus = $this->getOrder()->getLastStatus();?>
<?php $comment = $currentStatus->getComment()?>

<div class="box-left">
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4>Comments History</h4>
            </div>
            <fieldset><div id="order_history_block">
        <div id="history_form" class="order-history-form">
        <div>Add Order Comments</div>
     	<span class="field-row">
            <label class="normal" for="history_status">Status</label><br>
            <select name="history[status]" class="select" id="history_status">
                <?php foreach ($statuses as $value => $sort): ?>
                	 <?php if ($statuses[$currentStatus->getStatus()] <= $sort && $statuses[$currentStatus->getStatus()] != 3) : ?>
                			<option value="<?php echo $value; ?>"
                				<?php if($currentStatus->getStatus() == $value):?><?php echo "selected";?><?php endif; ?>>
                					<?php echo $value; ?>
                			</option>
          			  <?php endif; ?>
          		<?php endforeach;?>  
          	</select>
        </span>
        <span class="field-row">
            <label class="normal" for="history_comment">Comment</label>
            <textarea name="history[comment]" rows="3" cols="5" style="height:6em; width:99%;" id="history_comment"><?php echo $comment; ?></textarea>
        </span>
        <div class="f-right">
            <button id="submit_comment" title="Submit Comment" type="button" class="scalable save" onclick="changeAction('<?php echo $this->getCommentUrl(); ?>')" style=""><span><span><span>Submit Comment</span></span></span></button>        </div>
        <div class="clear"></div>
    </div>
    <div class="divider"></div>
</div>
</fieldset>
</div>
</div>