  <div class="box-left">
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4>Comments History</h4>
            </div>
            <fieldset>
            	<div id="order_history_block">
        			<div id="history_form" class="order-history-form">
        				<div>Add Order Comments</div>
        				<span class="field-row">
	           				<label class="normal" for="history_status">Status</label><br>
	            			<select name="history[status]" class="select" id="history_status">
	                            <option value="pending" selected="selected">Pending</option>
	                        </select>
        				</span>
        				<span class="field-row">
	            			<label class="normal" for="history_comment">Comment</label>
	            			<textarea name="history[comment]" rows="3" cols="5" style="height:6em; width:99%;" id="history_comment">
	            				
	            			</textarea>
        				</span>
        				
        				<div class="f-right">
            			<button title="Submit Comment" type="button" class="scalable save" ><span><span><span>Submit Comment</span></span></span>
            			</button>        
            		</div>
				</div>
			</fieldset>
        </div>
    </div>