<div class="container">
	<div class="form-buttons">
            <button id="submit_order_top_button" type="button" onclick="goBack()" class="scalable back" style="float: right;">
            	<span><span><span>Back</span></span></span>
            </button>
    </div>
	<div class="row mt-4">
		<div class="col-md-10 offset-md-1">
			<?php echo $this->getChild('order_customer')->toHtml() ?>
		</div>
	</div>
	<div class="row mt-4">
		<div class="col" style="overflow-y: scroll; height: 200px" id="orderProductContent">
			<?php echo $this->getChild('order_product')->toHtml() ?>
		</div>
	</div>
	<div class="row mt-5">
		<div class="col col-md-10 offset-md-1" id="productAddressContent">
			<?php echo $this->getChild('order_address')->toHtml() ?>
		</div>
	</div>
	<div class="row mt-5">
		<div class="col col-md-5 border offset-md-1" id="productOrderDetails">
			<?php echo $this->getChild('order_details')->toHtml() ?>
		</div>
	</div>

</div>

<script type="text/javascript">
	function goBack() {
		<?php $this->getUrl('*/*/index');?>		
	}
</script>